### ISSUE TITLE
Question about admin access

### ISSUE THREAD

**Issue by mthevoz** [adjaba/video-annotation-tool#41]
Hello, and thank you for providing this amazing tool!

I was playing around with it but still have not figured out how to launch the app with admin access, and am unable to edit the events or actions (I am quite unfamiliar with JS and React).

Would you be so kind as to provide instructions for doing that?

**Comment by adjaba** [comment]
Hi, thank you for your interest!

The admin portal is located in /admin, and the login is not implemented so you can enter the portal with any password. Some documentation on how to edit events and actions can be found [here](https://github.com/adjaba/video-annotation-tool#admin). Please let me know if you have any further questions!

**Comment by mthevoz** [comment]
Thank you for your answer. I see the AdminApp.js in the client/src/ folder but am still not sure how to launch the admin portal.

Would you mind showing what needs to be written in a terminal, similar to what there is in the Readme for running the development mode?

**Comment by adjaba** [comment]
There's nothing that needs to be written in the terminal - just the URL. When you launch the development mode, the website should launch in localhost:3000, in which case the admin portal will be located in localhost:3000/admin . Hope that helps!

**Comment by mthevoz** [comment]
Thank you, I was able to access the admin portal!

Unfortunately, nothing happens when I try to add events and actions, and I'm getting errors in my terminal:

```
HPM] Error occurred while trying to proxy request /api/events from localhost:3000 to http://localhost:3001 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)
[0] [HPM] Error occurred while trying to proxy request /api/actions from localhost:3000 to http://localhost:3001 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)
[0] [HPM] Error occurred while trying to proxy request /api/scenes from localhost:3000 to http://localhost:3001 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)
[0] [HPM] Error occurred while trying to proxy request /api/videos/ from localhost:3000 to http://localhost:3001 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)
[0] [HPM] Error occurred while trying to proxy request /api/events/ from localhost:3000 to http://localhost:3001 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)
[0] [HPM] Error occurred while trying to proxy request /api/scenes/ from localhost:3000 to http://localhost:3001 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)
[0] [HPM] Error occurred while trying to proxy request /api/actions/ from localhost:3000 to http://localhost:3001 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)
[0] [HPM] Error occurred while trying to proxy request /api/actions/add from localhost:3000 to http://localhost:3001 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)
[0] [HPM] Error occurred while trying to proxy request /api/actions/add from localhost:3000 to http://localhost:3001 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)
[0] [HPM] Error occurred while trying to proxy request /api/actions/add from localhost:3000 to http://localhost:3001 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)
```
Might it be because of this module import error at the start when I do `yarn start`?

```
yarn run v1.22.17
$ concurrently "cd client && yarn start" "cd server && yarn start"
$ yarn run nodemon src/index.js
$ react-scripts start
$ /home/XXX/video-annotation-tool/server/node_modules/.bin/nodemon src/index.js
[1] [nodemon] 1.19.1
[1] [nodemon] to restart at any time, enter `rs`
[1] [nodemon] watching: *.*
[1] [nodemon] starting `node src/index.js`
[1] internal/modules/cjs/loader.js:573
[1]     throw err;
[1]     ^
[1] 
[1] Error: Cannot find module '../build/better_sqlite3.node'
[1]     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:571:15)
[1]     at Function.Module._load (internal/modules/cjs/loader.js:497:25)
[1]     at Module.require (internal/modules/cjs/loader.js:626:17)
[1]     at require (internal/modules/cjs/helpers.js:20:18)
[1]     at Object.<anonymous> (/home/melik/Desktop/WePlaySport/Repos/video-annotation-tool/server/node_modules/better-sqlite3/lib/database.js:5:21)
[1]     at Module._compile (internal/modules/cjs/loader.js:678:30)
[1]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
[1]     at Module.load (internal/modules/cjs/loader.js:589:32)
[1]     at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
[1]     at Function.Module._load (internal/modules/cjs/loader.js:520:3)
[1] [nodemon] app crashed - waiting for file changes before starting...
[0] [HPM] Proxy created: /api  ->  http://localhost:3001
[0] Starting the development server...
```
